import type { Metadata, Viewport } from 'next'
import { Barlow_Condensed, Inter } from 'next/font/google'
import { COMPANY } from '@/lib/constants'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-inter',
  display: 'swap',
})

const barlowCondensed = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-barlow-condensed',
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL(COMPANY.site),
  title: {
    default: 'Alarmion — The Monitoring. Not The Hardware.',
    template: '%s · Alarmion',
  },
  description:
    'The ALD plugs into an outlet near your alarm and listens for your siren. Professional 24/7 monitoring for the alarm system you already own — from $9.99/month. No contract. No technician.',
  keywords: [
    'alarm monitoring',
    'professional monitoring',
    'ALD',
    'alarm listening device',
    'no contract alarm monitoring',
    'UL listed monitoring center',
  ],
  // Generated by scripts/make-logo-assets.js from the shield cropped out of
  // logo-transparent.png. The full lockup (shield + wordmark + tagline) is
  // illegible below ~64px, so the icons carry the shield alone, on white.
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/images/favicon-32.png', type: 'image/png', sizes: '32x32' },
    ],
    shortcut: '/favicon.ico',
    apple: '/images/apple-touch-icon.png',
  },
  openGraph: {
    type: 'website',
    url: COMPANY.site,
    siteName: 'Alarmion',
    title: 'Alarmion — The Monitoring. Not The Hardware.',
    description:
      'Professional 24/7 monitoring for the alarm you already own. From $9.99/month. No contract. No technician.',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Alarmion — The Monitoring. Not The Hardware.',
    description:
      'Professional 24/7 monitoring for the alarm you already own. From $9.99/month.',
  },
}

export const viewport: Viewport = {
  themeColor: '#080f22',
  colorScheme: 'dark',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${barlowCondensed.variable}`}
    >
      <head>
        {/* GSAP owns the reveal animations; without JS the .reveal class would
            leave sections permanently invisible. */}
        <noscript>
          <style>{`.reveal{opacity:1 !important;transform:none !important}`}</style>
        </noscript>
      </head>
      <body className="bg-navy-deep font-sans text-white antialiased">
        {children}
      </body>
    </html>
  )
}
